# Covariance Matrix

## Install libraries

In [1]:
import sys
!{sys.executable} -m pip install -r requirements.txt

    100% |████████████████████████████████| 12.2MB 1.3MB/s eta 0:00:01  4% |█▌                              | 583kB 12.2MB/s eta 0:00:01    14% |████▋                           | 1.8MB 13.6MB/s eta 0:00:01    29% |█████████▋                      | 3.6MB 12.8MB/s eta 0:00:01    45% |██████████████▋                 | 5.6MB 9.3MB/s eta 0:00:01    50% |████████████████▏               | 6.1MB 10.4MB/s eta 0:00:01    63% |████████████████████▌           | 7.8MB 13.5MB/s eta 0:00:01    77% |█████████████████████████       | 9.5MB 12.8MB/s eta 0:00:01    93% |█████████████████████████████▉  | 11.3MB 13.5MB/s eta 0:00:01    98% |███████████████████████████████▍| 11.9MB 12.4MB/s eta 0:00:01
tensorflow 1.3.0 requires tensorflow-tensorboard<0.2.0,>=0.1.0, which is not installed.
  Found existing installation: numpy 1.12.1
    Uninstalling numpy-1.12.1:
      Successfully uninstalled numpy-1.12.1


## Imports

In [2]:
import numpy as np
import quiz_tests

## Hints

### covariance matrix
If we have $m$ stock series, the covariance matrix is an $m \times m$ matrix containing the covariance between each pair of stocks.  We can use [numpy.cov](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html) to get the covariance.  We give it a 2D array in which each row is a stock series, and each column is an observation at the same period of time.

The covariance matrix $\mathbf{P} = 
\begin{bmatrix}
\sigma^2_{1,1} & ... & \sigma^2_{1,m} \\ 
... & ... & ...\\
\sigma_{m,1} & ... & \sigma^2_{m,m}  \\
\end{bmatrix}$

## Quiz

In [5]:
import numpy as np

def covariance_matrix(returns):
    """
    Create a function that takes the return series of a set of stocks
    and calculates the covariance matrix.
    
    Parameters
    ----------
    returns : numpy.ndarray
        2D array containing stock return series in each row.
                
    Returns
    -------
    x : np.ndarray
        A numpy ndarray containing the covariance matrix
    """
    
    # covariance matrix of returns
    #print(returns)
    return np.cov(returns)

In [6]:
quiz_tests.test_covariance_matrix(covariance_matrix)

Tests Passed


In [7]:
"""Test with a 3 simulated stock return series"""
days_per_year = 252
years = 3
total_days = days_per_year * years

return_market = np.random.normal(loc=0.05, scale=0.3, size=days_per_year)
return_1 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
return_2 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
return_3 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
returns = np.array([return_1, return_2, return_3])

"""try out your function"""
cov = covariance_matrix(returns)

print(f"The covariance matrix is \n{cov}")

The covariance matrix is 
[[0.09217784 0.09217785 0.09217786]
 [0.09217785 0.09217786 0.09217786]
 [0.09217786 0.09217786 0.09217787]]


If you're stuck, you can also check out the solution [here](m3l4_covariance_solution.ipynb)