# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

**Please note again that we are using 0 to represent heads, and 1 to represent tails.**

Use the proportions, numpy.mean(), you observed in your simulation data in order to guess the probabilities of the following outcomes.

In [1]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

Understand the code

In [2]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(5), 2)) #size=(int(1e6), 2))
tests

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 0]])

In [6]:
# sums of all tests
test_sums = tests.sum(axis=1)
test_sums

array([0, 1, 2, 2, 1])

In [11]:
# number of tests that produced exactly two heads
test_sums == 0

array([ True, False, False, False, False], dtype=bool)

In [12]:
# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.20000000000000001

Now do the real thing

In [13]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.250083

### 2. Three fair coin flips produce exactly one head

In [ ]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6), 3))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [14]:
# simulate 1 million tests of three biased coin flips
# hint: use np.random.choice()
tests = np.random.choice([0, 1], size=(int(1e6), 3), p=[0.6, 0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.28788200000000003

### 4. A die rolls an even number

In [15]:
# simulate 1 million tests of one die roll
tests = np.random.randint(1, 7, size=int(1e6))

# proportion of tests that produced an even number
(tests % 2 == 0).mean()

0.49945800000000001

### 5. Two dice roll a double

In [16]:
# simulate the first million die rolls
first = np.random.randint(1, 7, size=int(1e6))

# simulate the second million die rolls
second = np.random.randint(1, 7, size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.16672100000000001